production:
  url: <%= ENV["DATABASE_URL"] %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  database: famdish_backend_rails_development
  host: db
  username: postgres
  password: password
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

test:
  database: famdish_backend_rails_test
  host: db
  username: postgres
  password: password
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
